spring.application.name=customer-service
server.port=8080
spring.datasource.url=jdbc:h2:mem:customer-db
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
