spring.application.name=ebank-service
spring.datasource.url=jdbc:h2:mem:ebank-db
spring.h2.console.enabled=true
server.port=8081
spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false
